// country-facts.js - Fun facts for each country
const COUNTRY_FUN_FACTS = {
    'Afghanistan': 'Afghanistan is home to the world\'s largest Buddhist statues, the Buddhas of Bamiyan, which stood for over 1,500 years before being destroyed.',
    'Albania': 'Albania has more than 750,000 bunkers built during the communist era - roughly one bunker for every four inhabitants!',
    'Algeria': 'Algeria is the largest country in Africa and has the world\'s largest sand desert, the Sahara.',
    'Andorra': 'Andorra has no airport or railway station - visitors must enter by road from France or Spain.',
    'Angola': 'Angola is home to the second-largest waterfall in Africa, Kalandula Falls, which is 105 meters high.',
    'Antigua and Barbuda': 'Antigua boasts 365 beaches - one for every day of the year!',
    'Argentina': 'Argentina has the world\'s widest avenue, Avenida 9 de Julio in Buenos Aires, which spans 140 meters.',
    'Armenia': 'Armenia was the first country in the world to officially adopt Christianity as a state religion in 301 AD.',
    'Australia': 'Australia is home to 21 of the world\'s 25 most venomous snake species.',
    'Austria': 'The world\'s oldest zoo, Tiergarten Schönbrunn, was founded in Vienna, Austria in 1752.',
    'Azerbaijan': 'Azerbaijan has more mud volcanoes than any other country - over 400 of them!',
    'The Bahamas': 'The Bahamas is made up of 700 islands, but only 30 are inhabited.',
    'Bahrain': 'Bahrain\'s national tree, the Prosopis cineraria, can survive for over 100 years in the desert.',
    'Bangladesh': 'Bangladesh has the world\'s longest natural sea beach, Cox\'s Bazar, stretching 120 km.',
    'Barbados': 'Barbados is the birthplace of rum - the first distillery was established here in the 1640s.',
    'Belarus': 'Belarus is home to Europe\'s last primeval forest, the Białowieża Forest, where European bison still roam wild.',
    'Belgium': 'Belgium produces over 220,000 tons of chocolate per year - that\'s 22 kg per person!',
    'Belize': 'Belize has the only jaguar preserve in the world, the Cockscomb Basin Wildlife Sanctuary.',
    'Benin': 'Benin is considered the birthplace of Voodoo religion, which is still widely practiced today.',
    'Bhutan': 'Bhutan measures national success by Gross National Happiness rather than GDP.',
    'Bolivia': 'Bolivia has the world\'s largest salt flat, Salar de Uyuni, covering over 10,000 square kilometers.',
    'Bosnia and Herzegovina': 'Bosnia has one of the last remaining rainforests in Europe, Perućica.',
    'Botswana': 'Botswana has the world\'s largest elephant population, with over 130,000 elephants.',
    'Brazil': 'Brazil is home to 60% of the Amazon rainforest and contains more animal species than any other country.',
    'Brunei': 'Brunei\'s Sultan has the world\'s largest residential palace with 1,788 rooms.',
    'Bulgaria': 'Bulgaria is the world\'s leading producer of rose oil, used in perfumes worldwide.',
    'Burkina Faso': 'Burkina Faso means "Land of Honest People" in the local Mossi language.',
    'Burundi': 'Burundi has the world\'s longest freshwater lake, Lake Tanganyika, which is also the second-deepest.',
    'Cambodia': 'Angkor Wat in Cambodia is the largest religious monument in the world.',
    'Cameroon': 'Cameroon is called "Africa in miniature" because it has all the major African landscapes.',
    'Canada': 'Canada has more lakes than all other countries combined - over 3 million lakes!',
    'Cape Verde': 'Cape Verde was uninhabited until the Portuguese discovered it in 1456.',
    'Central African Republic': 'The Central African Republic is one of the most biologically diverse areas in Africa.',
    'Chad': 'Chad is home to Lake Chad, which has shrunk by 90% since the 1960s.',
    'Chile': 'Chile is home to the world\'s driest desert, the Atacama, where some areas haven\'t seen rain for 400 years.',
    'China': 'The Great Wall of China is over 21,000 km long and took more than 2,000 years to build.',
    'Colombia': 'Colombia has more bird species than any other country - over 1,900 species!',
    'Comoros': 'Comoros is the only country with three official languages: Arabic, French, and Comorian.',
    'Republic of the Congo': 'The Congo River is the world\'s deepest river, reaching depths of over 220 meters.',
    'Costa Rica': 'Costa Rica has no army - it was abolished in 1949 and the money goes to education instead.',
    'Croatia': 'Croatia invented the necktie - it comes from the Croatian word "kravata."',
    'Cuba': 'Cuba has the highest doctor-to-patient ratio in the world.',
    'Cyprus': 'Cyprus is the birthplace of Aphrodite, the Greek goddess of love.',
    'Czech Republic': 'The Czech Republic drinks more beer per capita than any other country.',
    'Democratic Republic of the Congo': 'The DRC has the world\'s largest reserves of cobalt, used in batteries.',
    'Denmark': 'Denmark consistently ranks as one of the happiest countries in the world.',
    'Djibouti': 'Djibouti\'s Lake Assal is the lowest point in Africa at 155 meters below sea level.',
    'Dominica': 'Dominica is known as the "Nature Island of the Caribbean" with 365 rivers.',
    'Dominican Republic': 'The Dominican Republic shares the island of Hispaniola with Haiti.',
    'Ecuador': 'Ecuador is named after the equator, which runs through the country.',
    'Egypt': 'Egypt is home to the Great Pyramid of Giza, the last remaining ancient wonder of the world.',
    'El Salvador': 'El Salvador is the smallest and most densely populated country in Central America.',
    'Equatorial Guinea': 'Equatorial Guinea is the only Spanish-speaking country in Africa.',
    'Eritrea': 'Eritrea has nine ethnic groups and is one of the most diverse countries in Africa.',
    'Estonia': 'Estonia has free public transport in its capital, Tallinn.',
    'Eswatini': 'Eswatini (formerly Swaziland) is one of the last absolute monarchies in Africa.',
    'Ethiopia': 'Ethiopia is the only African country that was never colonized.',
    'Fiji': 'Fiji is made up of 333 islands, but only 110 are inhabited.',
    'Finland': 'Finland has more saunas than cars - about 3.3 million saunas for 5.5 million people!',
    'France': 'France is the most visited country in the world with over 89 million tourists annually.',
    'Gabon': 'Gabon is one of the most forested countries in the world, with 88% forest cover.',
    'The Gambia': 'The Gambia is the smallest country in mainland Africa.',
    'Georgia': 'Georgia is the birthplace of wine - wine has been made here for over 8,000 years.',
    'Germany': 'Germany has over 1,500 different types of beer and 1,000 types of sausages.',
    'Ghana': 'Ghana was the first sub-Saharan African country to gain independence in 1957.',
    'Greece': 'Greece has more archaeological museums than any other country in the world.',
    'Grenada': 'Grenada is known as the "Island of Spice" and produces one-third of the world\'s nutmeg.',
    'Guatemala': 'Guatemala has 37 volcanoes, several of which are still active.',
    'Guinea': 'Guinea has one-third of the world\'s bauxite reserves (used to make aluminum).',
    'Guinea-Bissau': 'Guinea-Bissau is one of the world\'s largest cashew producers.',
    'Guyana': 'Guyana is the only English-speaking country in South America.',
    'Haiti': 'Haiti was the first country to permanently ban slavery in 1804.',
    'Honduras': 'Honduras has the world\'s second-largest barrier reef, the Mesoamerican Barrier Reef.',
    'Hungary': 'Hungary has won more Olympic gold medals per capita than any other country.',
    'Iceland': 'Iceland has no mosquitoes and is one of the only mosquito-free countries.',
    'India': 'India has more than 22 official languages and over 1,600 spoken languages.',
    'Indonesia': 'Indonesia is made up of over 17,000 islands and has the most active volcanoes in the world.',
    'Iran': 'Iran is home to one of the world\'s oldest civilizations, dating back to 3200 BC.',
    'Iraq': 'Iraq is home to the ancient city of Babylon, one of the Seven Wonders of the Ancient World.',
    'Republic of Ireland': 'Ireland has no snakes - St. Patrick allegedly drove them all out!',
    'Israel': 'Israel has more museums per capita than any other country.',
    'Italy': 'Italy has more UNESCO World Heritage Sites than any other country - 58 sites!',
    'Ivory Coast': 'Ivory Coast is the world\'s largest producer of cocoa beans.',
    'Jamaica': 'Jamaica is the birthplace of reggae music and Bob Marley.',
    'Japan': 'Japan has more than 6,800 islands, though only 430 are inhabited.',
    'Jordan': 'Jordan is home to Petra, one of the New Seven Wonders of the World.',
    'Kazakhstan': 'Kazakhstan is the world\'s largest landlocked country by area.',
    'Kenya': 'Kenya is home to the Great Migration, where 1.5 million wildebeest travel annually.',
    'Kiribati': 'Kiribati is the only country in all four hemispheres (North, South, East, West).',
    'Kuwait': 'Kuwait has one of the highest per capita incomes in the world due to oil reserves.',
    'Kyrgyzstan': 'Kyrgyzstan has more than 80 mountain peaks over 7,000 meters high.',
    'Laos': 'Laos is the most heavily bombed country per capita in history.',
    'Latvia': 'Latvia has the world\'s widest waterfall, Ventas Rumba, at 270 meters wide.',
    'Lebanon': 'Lebanon is home to the ancient city of Byblos, one of the oldest continuously inhabited cities.',
    'Lesotho': 'Lesotho is the only country in the world that lies entirely above 1,000 meters elevation.',
    'Liberia': 'Liberia was founded by freed American slaves in 1847.',
    'Libya': 'Libya has the world\'s largest proven oil reserves in Africa.',
    'Liechtenstein': 'Liechtenstein is the world\'s sixth smallest country and is doubly landlocked.',
    'Lithuania': 'Lithuania was the last pagan country in Europe, adopting Christianity only in 1387.',
    'Luxembourg': 'Luxembourg is the world\'s only remaining Grand Duchy.',
    'Madagascar': 'Madagascar is home to species found nowhere else on Earth - 90% are endemic.',
    'Malawi': 'Malawi\'s Lake Malawi has more fish species than any other lake in the world.',
    'Malaysia': 'Malaysia is home to the world\'s oldest rainforest, over 130 million years old.',
    'Maldives': 'The Maldives is the lowest-lying country in the world, with an average elevation of 1.5 meters.',
    'Mali': 'Mali was home to one of the richest people in history, Mansa Musa.',
    'Malta': 'Malta has three UNESCO World Heritage Sites despite being one of the world\'s smallest countries.',
    'Marshall Islands': 'The Marshall Islands were used as a nuclear test site by the US during the Cold War.',
    'Mauritania': 'Mauritania has the world\'s longest train - the iron ore train is up to 3 km long!',
    'Mauritius': 'Mauritius was the only known home of the extinct dodo bird.',
    'Mexico': 'Mexico City is sinking at a rate of 50 cm per year due to groundwater extraction.',
    'Federated States of Micronesia': 'Micronesia contains 607 islands spread across the Pacific Ocean.',
    'Moldova': 'Moldova has the largest wine cellar in the world, with over 2 million bottles.',
    'Monaco': 'Monaco is the world\'s second smallest country and the most densely populated.',
    'Mongolia': 'Mongolia has the world\'s lowest population density - only 2 people per square kilometer.',
    'Montenegro': 'Montenegro has Europe\'s deepest canyon, the Tara River Canyon, at 1,300 meters deep.',
    'Morocco': 'Morocco has the world\'s oldest operating university, founded in 859 AD.',
    'Mozambique': 'Mozambique is home to the quirky Maputo Special Reserve with the rare coastal elephants.',
    'Myanmar': 'Myanmar has over 2,000 ancient temples in the Bagan Archaeological Zone.',
    'Namibia': 'Namibia has the world\'s highest sand dunes, some reaching 380 meters high.',
    'Nauru': 'Nauru is the world\'s smallest island nation at just 21 square kilometers.',
    'Nepal': 'Nepal has eight of the world\'s ten highest mountains, including Mount Everest.',
    'Netherlands': 'The Netherlands has more bicycles than people - over 23 million bikes!',
    'New Zealand': 'New Zealand was the last major landmass to be settled by humans.',
    'Nicaragua': 'Nicaragua has both Pacific and Caribbean coastlines.',
    'Niger': 'Niger is named after the Niger River, which flows through the country.',
    'Nigeria': 'Nigeria has the largest film industry in Africa, called "Nollywood."',
    'North Korea': 'North Korea has its own time zone that is 30 minutes different from South Korea.',
    'North Macedonia': 'North Macedonia is home to Lake Ohrid, one of Europe\'s oldest and deepest lakes.',
    'Norway': 'Norway has the world\'s longest road tunnel, the Lærdal Tunnel, at 24.5 km long.',
    'Oman': 'Oman has over 500 forts, the most per capita in the Arab world.',
    'Pakistan': 'Pakistan has the world\'s second-highest mountain, K2, at 8,611 meters.',
    'Palau': 'Palau has the world\'s first shark sanctuary, established in 2009.',
    'Panama': 'The Panama Canal connects the Atlantic and Pacific Oceans and handles 6% of world trade.',
    'Papua New Guinea': 'Papua New Guinea has over 800 languages - more than any other country!',
    'Paraguay': 'Paraguay\'s flag is unique - it has different emblems on each side.',
    'Peru': 'Peru is home to Machu Picchu, the mysterious "Lost City of the Incas."',
    'Philippines': 'The Philippines has over 7,600 islands, but only 2,000 are inhabited.',
    'Poland': 'Poland has 17 UNESCO World Heritage Sites, including the historic salt mines.',
    'Portugal': 'Portugal is the world\'s largest cork producer, making half of the world\'s cork.',
    'Qatar': 'Qatar has the world\'s highest GDP per capita and no income tax.',
    'Romania': 'Romania is home to Dracula\'s Castle (Bran Castle) and the Carpathian Mountains.',
    'Russia': 'Russia spans 11 time zones and is the world\'s largest country by area.',
    'Rwanda': 'Rwanda is one of only three countries where mountain gorillas can be found in the wild.',
    'Saint Kitts and Nevis': 'Saint Kitts and Nevis is the smallest country in the Western Hemisphere.',
    'Saint Lucia': 'Saint Lucia is the only country named after a woman, Saint Lucy.',
    'Saint Vincent and the Grenadines': 'Most of Pirates of the Caribbean was filmed in Saint Vincent and the Grenadines.',
    'Samoa': 'Samoa was one of the last places on Earth to be colonized by humans.',
    'San Marino': 'San Marino is the world\'s oldest republic, founded in 301 AD.',
    'Sao Tome and Principe': 'São Tomé and Príncipe are volcanic islands on the equator in the Gulf of Guinea.',
    'Saudi Arabia': 'Saudi Arabia has no rivers and gets most of its water from desalination plants.',
    'Senegal': 'Senegal has Africa\'s westernmost point, the Cap-Vert Peninsula.',
    'Serbia': 'Serbia has one of the oldest towns in Europe, Vinča, dating back to 5700 BC.',
    'Seychelles': 'Seychelles has two UNESCO World Heritage Sites despite being tiny.',
    'Sierra Leone': 'Sierra Leone has the world\'s third-largest natural harbor.',
    'Singapore': 'Singapore gained independence against its will in 1965 after being expelled from Malaysia!',
    'Slovakia': 'Slovakia has the highest number of castles per capita in the world.',
    'Slovenia': 'Slovenia has more than 10,000 caves, including the famous Postojna Cave.',
    'Solomon Islands': 'The Solomon Islands have some of the world\'s best diving sites with WWII wreckage.',
    'Somalia': 'Somalia has the longest coastline in mainland Africa at 3,300 km.',
    'South Africa': 'South Africa is the only country with three capital cities: Pretoria, Cape Town, and Bloemfontein.',
    'South Korea': 'South Korea has the world\'s fastest internet speeds.',
    'South Sudan': 'South Sudan is the world\'s youngest country, gaining independence in 2011.',
    'Spain': 'Spain produces nearly half of the world\'s olive oil.',
    'Sri Lanka': 'Sri Lanka was the first country to have a female prime minister, in 1960.',
    'Sudan': 'Sudan has more pyramids than Egypt - over 200 ancient pyramids!',
    'Suriname': 'Suriname is the smallest country in South America.',
    'Sweden': 'Sweden has the world\'s first ice hotel, rebuilt every winter.',
    'Switzerland': 'Switzerland has 7,000 lakes and is one of the world\'s most mountainous countries.',
    'Syria': 'Syria is home to one of the world\'s oldest civilizations, dating back to 10,000 BC.',
    'Tajikistan': '93% of Tajikistan is mountainous, with half its territory above 3,000 meters.',
    'Tanzania': 'Tanzania is home to Mount Kilimanjaro, Africa\'s highest mountain at 5,895 meters.',
    'Thailand': 'Thailand is the only Southeast Asian country never colonized by Europeans.',
    'East Timor': 'East Timor is one of only two predominantly Catholic countries in Asia.',
    'Togo': 'Togo is one of the smallest countries in Africa, only 57,000 square kilometers.',
    'Tonga': 'Tonga is the only country in Oceania never formally colonized.',
    'Trinidad and Tobago': 'Trinidad and Tobago has the world\'s largest natural deposit of asphalt.',
    'Tunisia': 'Tunisia is home to the ancient city of Carthage, once Rome\'s greatest rival.',
    'Turkey': 'Turkey straddles two continents, Europe and Asia, divided by the Bosphorus Strait.',
    'Turkmenistan': 'Turkmenistan has the "Door to Hell," a burning gas crater that has been burning since 1971.',
    'Tuvalu': 'Tuvalu is the world\'s fourth smallest country and is slowly sinking due to rising sea levels.',
    'Uganda': 'Uganda is the source of the Nile River and is called the "Pearl of Africa" for its natural beauty.',
    'Ukraine': 'Ukraine is the largest country entirely in Europe and has the world\'s deepest metro station.',
    'United Arab Emirates': 'The UAE has the world\'s tallest building, the Burj Khalifa, at 828 meters.',
    'United Kingdom': 'The UK has more than 300 languages spoken in London alone.',
    'United States': 'The United States has no official language at the federal level.',
    'Uruguay': 'Uruguay was the first country to provide every schoolchild with a free laptop.',
    'Uzbekistan': 'Uzbekistan is doubly landlocked - you have to cross two countries to reach an ocean.',
    'Vanuatu': 'Vanuatu has over 100 languages for a population of only 300,000 people!',
    'Vatican City': 'Vatican City is the world\'s smallest country at just 0.44 square kilometers.',
    'Venezuela': 'Venezuela has the world\'s highest waterfall, Angel Falls, at 979 meters.',
    'Vietnam': 'Vietnam is the world\'s largest exporter of cashews and black pepper.',
    'Yemen': 'Yemen has been inhabited for over 5,000 years and is one of the oldest civilizations.',
    'Zambia': 'Zambia is home to Victoria Falls, one of the Seven Natural Wonders of the World.',
    'Zimbabwe': 'Zimbabwe shares Victoria Falls with Zambia and has a remarkably diverse wildlife population.'
};