// Country-specific hints data
const COUNTRY_HINTS = {
  "Afghanistan": { capital: "Kabul", population: "over 38 million", borders: 6 },
  "Albania": { capital: "Tirana", population: "between 2 and 5 million", borders: 4 },
  "Algeria": { capital: "Algiers", population: "over 40 million", borders: 7 },
  "Andorra": { capital: "Andorra la Vella", population: "under 100,000", borders: 2 },
  "Angola": { capital: "Luanda", population: "between 20 and 50 million", borders: 4 },
  "Argentina": { capital: "Buenos Aires", population: "over 40 million", borders: 5 },
  "Armenia": { capital: "Yerevan", population: "between 2 and 5 million", borders: 4 },
  "Australia": { capital: "Canberra", population: "between 20 and 50 million", borders: 0 },
  "Austria": { capital: "Vienna", population: "between 5 and 10 million", borders: 8 },
  "Azerbaijan": { capital: "Baku", population: "between 5 and 10 million", borders: 5 },
  "Bahamas": { capital: "Nassau", population: "between 100,000 and 500,000", borders: 0 },
  "Bahrain": { capital: "Manama", population: "between 1 and 2 million", borders: 1 },
  "Bangladesh": { capital: "Dhaka", population: "over 160 million", borders: 2 },
  "Barbados": { capital: "Bridgetown", population: "between 100,000 and 500,000", borders: 0 },
  "Belarus": { capital: "Minsk", population: "between 5 and 10 million", borders: 5 },
  "Belgium": { capital: "Brussels", population: "between 10 and 20 million", borders: 4 },
  "Belize": { capital: "Belmopan", population: "between 100,000 and 500,000", borders: 2 },
  "Benin": { capital: "Porto-Novo", population: "between 10 and 20 million", borders: 4 },
  "Bhutan": { capital: "Thimphu", population: "between 500,000 and 1 million", borders: 2 },
  "Bolivia": { capital: "Sucre", population: "between 10 and 20 million", borders: 5 },
  "Bosnia and Herzegovina": { capital: "Sarajevo", population: "between 2 and 5 million", borders: 3 },
  "Botswana": { capital: "Gaborone", population: "between 2 and 5 million", borders: 4 },
  "Brazil": { capital: "Brasília", population: "over 200 million", borders: 10 },
  "Brunei": { capital: "Bandar Seri Begawan", population: "between 100,000 and 500,000", borders: 1 },
  "Bulgaria": { capital: "Sofia", population: "between 5 and 10 million", borders: 5 },
  "Burkina Faso": { capital: "Ouagadougou", population: "between 20 and 50 million", borders: 6 },
  "Burundi": { capital: "Bujumbura", population: "between 10 and 20 million", borders: 3 },
  "Cambodia": { capital: "Phnom Penh", population: "between 10 and 20 million", borders: 3 },
  "Cameroon": { capital: "Yaoundé", population: "between 20 and 50 million", borders: 6 },
  "Canada": { capital: "Ottawa", population: "between 20 and 50 million", borders: 1 },
  "Cape Verde": { capital: "Praia", population: "between 100,000 and 500,000", borders: 0 },
  "Central African Republic": { capital: "Bangui", population: "between 2 and 5 million", borders: 6 },
  "Chad": { capital: "N'Djamena", population: "between 10 and 20 million", borders: 6 },
  "Chile": { capital: "Santiago", population: "between 10 and 20 million", borders: 3 },
  "China": { capital: "Beijing", population: "over 1 billion", borders: 14 },
  "Colombia": { capital: "Bogotá", population: "between 50 and 100 million", borders: 5 },
  "Comoros": { capital: "Moroni", population: "between 500,000 and 1 million", borders: 0 },
  "Congo": { capital: "Brazzaville", population: "between 5 and 10 million", borders: 5 },
  "Costa Rica": { capital: "San José", population: "between 5 and 10 million", borders: 2 },
  "Croatia": { capital: "Zagreb", population: "between 2 and 5 million", borders: 5 },
  "Cuba": { capital: "Havana", population: "between 10 and 20 million", borders: 0 },
  "Cyprus": { capital: "Nicosia", population: "between 1 and 2 million", borders: 0 },
  "Czech Republic": { capital: "Prague", population: "between 10 and 20 million", borders: 4 },
  "Denmark": { capital: "Copenhagen", population: "between 5 and 10 million", borders: 1 },
  "Djibouti": { capital: "Djibouti City", population: "between 500,000 and 1 million", borders: 3 },
  "Dominica": { capital: "Roseau", population: "under 100,000", borders: 0 },
  "Dominican Republic": { capital: "Santo Domingo", population: "between 10 and 20 million", borders: 1 },
  "Ecuador": { capital: "Quito", population: "between 10 and 20 million", borders: 2 },
  "Egypt": { capital: "Cairo", population: "over 100 million", borders: 4 },
  "El Salvador": { capital: "San Salvador", population: "between 5 and 10 million", borders: 2 },
  "Equatorial Guinea": { capital: "Malabo", population: "between 1 and 2 million", borders: 2 },
  "Eritrea": { capital: "Asmara", population: "between 5 and 10 million", borders: 3 },
  "Estonia": { capital: "Tallinn", population: "between 1 and 2 million", borders: 2 },
  "Ethiopia": { capital: "Addis Ababa", population: "over 100 million", borders: 6 },
  "Fiji": { capital: "Suva", population: "between 500,000 and 1 million", borders: 0 },
  "Finland": { capital: "Helsinki", population: "between 5 and 10 million", borders: 3 },
  "France": { capital: "Paris", population: "between 50 and 100 million", borders: 8 },
  "Gabon": { capital: "Libreville", population: "between 2 and 5 million", borders: 3 },
  "Gambia": { capital: "Banjul", population: "between 2 and 5 million", borders: 1 },
  "Georgia": { capital: "Tbilisi", population: "between 2 and 5 million", borders: 4 },
  "Germany": { capital: "Berlin", population: "over 80 million", borders: 9 },
  "Ghana": { capital: "Accra", population: "between 20 and 50 million", borders: 3 },
  "Greece": { capital: "Athens", population: "between 10 and 20 million", borders: 4 },
  "Grenada": { capital: "St. George's", population: "between 100,000 and 500,000", borders: 0 },
  "Guatemala": { capital: "Guatemala City", population: "between 10 and 20 million", borders: 4 },
  "Guinea": { capital: "Conakry", population: "between 10 and 20 million", borders: 6 },
  "Guinea-Bissau": { capital: "Bissau", population: "between 1 and 2 million", borders: 2 },
  "Guyana": { capital: "Georgetown", population: "between 500,000 and 1 million", borders: 3 },
  "Haiti": { capital: "Port-au-Prince", population: "between 10 and 20 million", borders: 1 },
  "Honduras": { capital: "Tegucigalpa", population: "between 5 and 10 million", borders: 3 },
  "Hungary": { capital: "Budapest", population: "between 5 and 10 million", borders: 7 },
  "Iceland": { capital: "Reykjavík", population: "between 100,000 and 500,000", borders: 0 },
  "India": { capital: "New Delhi", population: "over 1 billion", borders: 6 },
  "Indonesia": { capital: "Jakarta", population: "over 250 million", borders: 3 },
  "Iran": { capital: "Tehran", population: "over 80 million", borders: 7 },
  "Iraq": { capital: "Baghdad", population: "between 20 and 50 million", borders: 6 },
  "Ireland": { capital: "Dublin", population: "between 5 and 10 million", borders: 1 },
  "Israel": { capital: "Jerusalem", population: "between 5 and 10 million", borders: 5 },
  "Italy": { capital: "Rome", population: "between 50 and 100 million", borders: 6 },
  "Jamaica": { capital: "Kingston", population: "between 2 and 5 million", borders: 0 },
  "Japan": { capital: "Tokyo", population: "over 120 million", borders: 0 },
  "Jordan": { capital: "Amman", population: "between 10 and 20 million", borders: 5 },
  "Kazakhstan": { capital: "Astana", population: "between 10 and 20 million", borders: 5 },
  "Kenya": { capital: "Nairobi", population: "between 50 and 100 million", borders: 5 },
  "Kiribati": { capital: "South Tarawa", population: "between 100,000 and 500,000", borders: 0 },
  "Kosovo": { capital: "Pristina", population: "between 1 and 2 million", borders: 4 },
  "Kuwait": { capital: "Kuwait City", population: "between 2 and 5 million", borders: 2 },
  "Kyrgyzstan": { capital: "Bishkek", population: "between 5 and 10 million", borders: 4 },
  "Laos": { capital: "Vientiane", population: "between 5 and 10 million", borders: 5 },
  "Latvia": { capital: "Riga", population: "between 1 and 2 million", borders: 4 },
  "Lebanon": { capital: "Beirut", population: "between 5 and 10 million", borders: 2 },
  "Lesotho": { capital: "Maseru", population: "between 2 and 5 million", borders: 1 },
  "Liberia": { capital: "Monrovia", population: "between 2 and 5 million", borders: 3 },
  "Libya": { capital: "Tripoli", population: "between 5 and 10 million", borders: 6 },
  "Liechtenstein": { capital: "Vaduz", population: "under 100,000", borders: 2 },
  "Lithuania": { capital: "Vilnius", population: "between 2 and 5 million", borders: 4 },
  "Luxembourg": { capital: "Luxembourg City", population: "between 500,000 and 1 million", borders: 3 },
  "Madagascar": { capital: "Antananarivo", population: "between 20 and 50 million", borders: 0 },
  "Malawi": { capital: "Lilongwe", population: "between 10 and 20 million", borders: 3 },
  "Malaysia": { capital: "Kuala Lumpur", population: "between 20 and 50 million", borders: 3 },
  "Maldives": { capital: "Malé", population: "between 100,000 and 500,000", borders: 0 },
  "Mali": { capital: "Bamako", population: "between 10 and 20 million", borders: 7 },
  "Malta": { capital: "Valletta", population: "between 100,000 and 500,000", borders: 0 },
  "Marshall Islands": { capital: "Majuro", population: "under 100,000", borders: 0 },
  "Mauritania": { capital: "Nouakchott", population: "between 2 and 5 million", borders: 4 },
  "Mauritius": { capital: "Port Louis", population: "between 1 and 2 million", borders: 0 },
  "Mexico": { capital: "Mexico City", population: "over 120 million", borders: 3 },
  "Micronesia": { capital: "Palikir", population: "between 100,000 and 500,000", borders: 0 },
  "Moldova": { capital: "Chișinău", population: "between 2 and 5 million", borders: 2 },
  "Monaco": { capital: "Monaco City", population: "under 100,000", borders: 1 },
  "Mongolia": { capital: "Ulaanbaatar", population: "between 2 and 5 million", borders: 2 },
  "Montenegro": { capital: "Podgorica", population: "between 500,000 and 1 million", borders: 5 },
  "Morocco": { capital: "Rabat", population: "between 20 and 50 million", borders: 3 },
  "Mozambique": { capital: "Maputo", population: "between 20 and 50 million", borders: 6 },
  "Myanmar": { capital: "Naypyidaw", population: "between 50 and 100 million", borders: 5 },
  "Namibia": { capital: "Windhoek", population: "between 2 and 5 million", borders: 4 },
  "Nauru": { capital: "Yaren", population: "under 100,000", borders: 0 },
  "Nepal": { capital: "Kathmandu", population: "between 20 and 50 million", borders: 2 },
  "Netherlands": { capital: "Amsterdam", population: "between 10 and 20 million", borders: 2 },
  "New Zealand": { capital: "Wellington", population: "between 2 and 5 million", borders: 0 },
  "Nicaragua": { capital: "Managua", population: "between 5 and 10 million", borders: 2 },
  "Niger": { capital: "Niamey", population: "between 20 and 50 million", borders: 7 },
  "Nigeria": { capital: "Abuja", population: "over 200 million", borders: 4 },
  "North Korea": { capital: "Pyongyang", population: "between 20 and 50 million", borders: 3 },
  "North Macedonia": { capital: "Skopje", population: "between 2 and 5 million", borders: 5 },
  "Norway": { capital: "Oslo", population: "between 5 and 10 million", borders: 3 },
  "Oman": { capital: "Muscat", population: "between 5 and 10 million", borders: 3 },
  "Pakistan": { capital: "Islamabad", population: "over 200 million", borders: 4 },
  "Palau": { capital: "Ngerulmud", population: "under 100,000", borders: 0 },
  "Palestine": { capital: "Ramallah", population: "between 5 and 10 million", borders: 2 },
  "Panama": { capital: "Panama City", population: "between 2 and 5 million", borders: 2 },
  "Papua New Guinea": { capital: "Port Moresby", population: "between 5 and 10 million", borders: 1 },
  "Paraguay": { capital: "Asunción", population: "between 5 and 10 million", borders: 3 },
  "Peru": { capital: "Lima", population: "between 20 and 50 million", borders: 5 },
  "Philippines": { capital: "Manila", population: "over 100 million", borders: 0 },
  "Poland": { capital: "Warsaw", population: "between 20 and 50 million", borders: 7 },
  "Portugal": { capital: "Lisbon", population: "between 10 and 20 million", borders: 1 },
  "Qatar": { capital: "Doha", population: "between 2 and 5 million", borders: 1 },
  "Romania": { capital: "Bucharest", population: "between 10 and 20 million", borders: 5 },
  "Russia": { capital: "Moscow", population: "over 140 million", borders: 14 },
  "Rwanda": { capital: "Kigali", population: "between 10 and 20 million", borders: 4 },
  "Saint Kitts and Nevis": { capital: "Basseterre", population: "under 100,000", borders: 0 },
  "Saint Lucia": { capital: "Castries", population: "between 100,000 and 500,000", borders: 0 },
  "Saint Vincent and the Grenadines": { capital: "Kingstown", population: "between 100,000 and 500,000", borders: 0 },
  "Samoa": { capital: "Apia", population: "between 100,000 and 500,000", borders: 0 },
  "San Marino": { capital: "City of San Marino", population: "under 100,000", borders: 1 },
  "Saudi Arabia": { capital: "Riyadh", population: "between 20 and 50 million", borders: 4 },
  "Senegal": { capital: "Dakar", population: "between 10 and 20 million", borders: 5 },
  "Serbia": { capital: "Belgrade", population: "between 5 and 10 million", borders: 8 },
  "Seychelles": { capital: "Victoria", population: "between 100,000 and 500,000", borders: 0 },
  "Sierra Leone": { capital: "Freetown", population: "between 5 and 10 million", borders: 2 },
  "Singapore": { capital: "Singapore", population: "between 5 and 10 million", borders: 1 },
  "Slovakia": { capital: "Bratislava", population: "between 5 and 10 million", borders: 5 },
  "Slovenia": { capital: "Ljubljana", population: "between 2 and 5 million", borders: 4 },
  "Solomon Islands": { capital: "Honiara", population: "between 500,000 and 1 million", borders: 0 },
  "Somalia": { capital: "Mogadishu", population: "between 10 and 20 million", borders: 3 },
  "South Africa": { capital: "Pretoria", population: "between 50 and 100 million", borders: 6 },
  "South Korea": { capital: "Seoul", population: "between 50 and 100 million", borders: 1 },
  "South Sudan": { capital: "Juba", population: "between 10 and 20 million", borders: 6 },
  "Spain": { capital: "Madrid", population: "between 20 and 50 million", borders: 5 },
  "Sri Lanka": { capital: "Colombo", population: "between 20 and 50 million", borders: 0 },
  "Sudan": { capital: "Khartoum", population: "between 20 and 50 million", borders: 7 },
  "Suriname": { capital: "Paramaribo", population: "between 500,000 and 1 million", borders: 3 },
  "Sweden": { capital: "Stockholm", population: "between 10 and 20 million", borders: 2 },
  "Switzerland": { capital: "Bern", population: "between 5 and 10 million", borders: 5 },
  "Syria": { capital: "Damascus", population: "between 10 and 20 million", borders: 5 },
  "Taiwan": { capital: "Taipei", population: "between 20 and 50 million", borders: 0 },
  "Tajikistan": { capital: "Dushanbe", population: "between 5 and 10 million", borders: 4 },
  "Tanzania": { capital: "Dodoma", population: "between 50 and 100 million", borders: 8 },
  "Thailand": { capital: "Bangkok", population: "between 50 and 100 million", borders: 4 },
  "East Timor": { capital: "Dili", population: "between 1 and 2 million", borders: 1 },
  "Togo": { capital: "Lomé", population: "between 5 and 10 million", borders: 3 },
  "Tonga": { capital: "Nuku'alofa", population: "between 100,000 and 500,000", borders: 0 },
  "Trinidad and Tobago": { capital: "Port of Spain", population: "between 1 and 2 million", borders: 0 },
  "Tunisia": { capital: "Tunis", population: "between 10 and 20 million", borders: 2 },
  "Turkey": { capital: "Ankara", population: "over 80 million", borders: 8 },
  "Turkmenistan": { capital: "Ashgabat", population: "between 5 and 10 million", borders: 4 },
  "Tuvalu": { capital: "Funafuti", population: "under 100,000", borders: 0 },
  "Uganda": { capital: "Kampala", population: "between 20 and 50 million", borders: 5 },
  "Ukraine": { capital: "Kyiv", population: "between 20 and 50 million", borders: 7 },
  "United Arab Emirates": { capital: "Abu Dhabi", population: "between 5 and 10 million", borders: 2 },
  "United Kingdom": { capital: "London", population: "between 50 and 100 million", borders: 1 },
  "United States": { capital: "Washington, D.C.", population: "over 320 million", borders: 2 },
  "Uruguay": { capital: "Montevideo", population: "between 2 and 5 million", borders: 2 },
  "Uzbekistan": { capital: "Tashkent", population: "between 20 and 50 million", borders: 5 },
  "Vanuatu": { capital: "Port Vila", population: "between 100,000 and 500,000", borders: 0 },
  "Vatican City": { capital: "Vatican City", population: "under 100,000", borders: 1 },
  "Venezuela": { capital: "Caracas", population: "between 20 and 50 million", borders: 3 },
  "Vietnam": { capital: "Hanoi", population: "over 90 million", borders: 3 },
  "Yemen": { capital: "Sana'a", population: "between 20 and 50 million", borders: 2 },
  "Zambia": { capital: "Lusaka", population: "between 10 and 20 million", borders: 8 },
  "Zimbabwe": { capital: "Harare", population: "between 10 and 20 million", borders: 4 }
};